# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3d443a2fedffcb16ae0b5ab23da1dfcd57959542e3e3a9d737230ada431f10285db12466bc87ac069bafed204625e37b0861b8d74a7e4632f14bab96a91f600

test:
  secret_key_base: f11cf10b3e27a47ed1b84d94ef935b69e729a01623d177b7df8ae9f7411b7c3295b6a8c33cca18963217ae2d9ddfe2b38738163ba3054b516ab142383352f863

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
